### ISSUE TITLE
Issue Template for questions?

### ISSUE THREAD

**Issue by RyKilleen** [SeanKilleen/ama#11]
The blank page can be scary, an issue template might help folks get started!

**Comment by SeanKilleen** [comment]
Interesting! What would you suggest go in the template? I'm not opposed, but the site is "ask me anything" so I think i'd be interested on how to standardize that. Do you mean like a welcoming message in a comment?

**Comment by SeanKilleen** [comment]
Going to close this for now but interested to hear if you have any suggestions for a template and happy to reopen anytime
