### ISSUE TITLE
What should a new tech lead focus on for the first 90 days?

### ISSUE THREAD

**Issue by matthewdeanmartin** [SeanKilleen/ama#15]
Imagine a stereotypical dev lead, brought in from the outside of the org, leading a small team to build a website. This hypothetical scenario has suddenly become very relevant to me.

**Comment by SeanKilleen** [comment]
Thanks for writing in! I want to think about this a little more deeply, but for starters I have this post from a few years back: [A Running Checklist for Software Team Leads](https://seankilleen.com/2015/12/a-running-checklist-for-team-leads/) that might be a good jumping off point.

**Comment by SeanKilleen** [comment]
Also I just realized, one of your tweets is quoted in it! 😄 what a great small world.

**Comment by SeanKilleen** [comment]
@matthewdeanmartin I'm going to close this for my own inbox-zero sanity's sake, but please let me know if you've got follow-up questions or anything you'd like me to expound upon. I appreciate you asking! 👍
