### ISSUE TITLE
How should employers handle moonlighting remote workers?

### ISSUE THREAD

**Issue by matthewdeanmartin** [SeanKilleen/ama#19]
There are more and more reports of people working remote taking multiple tech jobs from home.

Is this a new normal, a new problem or a new solution (sharing scarce techies across more employers)?

**Comment by SeanKilleen** [comment]
Hey @matthewdeanmartin! I totally missed this from a while ago -- sorry about that.

A few random thoughts on this below:

* I think moonlighting should generally be acceptable, provided there is clear communication and moonlighting does not compete with the needs or interests of the employer. I've been able to work out agreements with past employers when I've done extra product work or consulting work that is not work they'd ever want to do. So in general, I'm pro-moonlighting. In fact, sometimes if I take on a small engagement or project outside of my employer, it can be an excellent offset for organizational constraints and helps keep me engaged and happy as a professional. It can replenish my reserves.
* I think when companies pay market rate for your brainpower, they deserve to get your full and undivided attention. I think that if you're moonlighting a second almost full-time tech job and completely burned out a both, it's not a tenable solution.
* On the flip side, I don't think that being salaried at an organization means they own your brain 24/7.  
* I think moonlighting without clear communication -- and particularly with the intent to deceive -- hurts our entire industry. If employers can't trust knowledge workers to operate with integrity, we might see a resurgence of low-trust environments which hurts everyone -- employees, employers, and customers.

As a manager / leader, if I ran into such an issue, my process would probably be:

* A blunt conversation where we try to see if everyone's goals can be achieved, ensuring the employee knows I'm not an enemy of moonlighting or trying to claim their brain 24/7.
* If my expectations are not met for someone's performance, I'd let them know about that in the standard way I'd discuss those things. If I notice that in combination with any clear moonlighting trust violations, it would probably be time to involve HR.
* Multiple instances of this would likely lead for me to advocate for discipline including termination.

Let me know if you've got any follow up questions / thoughts. Thanks!
