### ISSUE TITLE
OGCS on new computer

### ISSUE THREAD

**Issue by dvonjr** [SeanKilleen/ama#21]
I had Outlook to Google Calendar Sync on a Laptop that died or will not boot to Windows. I have a backup Laptop that I need to put OGCS on. I have donated to be able to hide the splash screen on the dead Laptop but don't want to donate again just to hide the splash screen on the backup Laptop. Is there a way to move my account to the backup Laptop so I don't have to donate again?

Donation Sent
May 19, 2021 at 7:25:04 AM PDTTransaction ID: 3FB50855VA041144D
Payment Status: COMPLETED
Gross amount
-£5.00 GBP

**Comment by SeanKilleen** [comment]
Hi! I'm not actually a maintainer of that software, though I use it daily and have happily donated to it to unlock its full functionality, probably multiple times at this point.

You may want to try your question over at https://github.com/phw198/OutlookGoogleCalendarSync/issues
